# 2주차

### 선형회귀모형

In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [2]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [11]:
x_train, x_train.shape,y_train, y_train.shape

(tensor([[1.],
         [2.],
         [3.]]),
 torch.Size([3, 1]),
 tensor([[2.],
         [4.],
         [6.]]),
 torch.Size([3, 1]))

#### y = Wx + b

In [26]:
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [17]:
b = torch.zeros(1, requires_grad =True)
print(b)

tensor([0.], requires_grad=True)


In [18]:
y_hat = W*x_train + b
y_hat

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

In [29]:
cost = torch.mean((y_train-y_hat)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [30]:
optimizer = optim.SGD([W,b], lr=0.01)

In [32]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [36]:

# 데이터 
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad= True)
b = torch.zeros(1, requires_grad=True)
# Optimizer 설정
optimizer = optim.SGD([W, b], lr = 0.01)

nb_epochs = 1999 #반복수
for epoch in range(nb_epochs +1):
    # H(x) 계산
    y_hat = x_train*W + b
    # cost 계산
    cost = torch.mean((y_hat - y_train)**2)
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 100번마다 로그 출력
    if epoch % 100 ==0:
        print("Epoch:{:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}".format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch:   0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch: 100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch: 200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch: 300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch: 400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch: 500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch: 600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch: 700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch: 800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch: 900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch:1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch:1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch:1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch:1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch:1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch:1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch:1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch:1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch:1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch:1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

#### nn.linear

In [37]:
input_dim = 1
output_dim = 1

model = nn.Linear(input_dim, output_dim)

In [ ]:
# cost = F.mse_loss(y_hat, y_train)

In [38]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.1863]], requires_grad=True), Parameter containing:
tensor([-0.4795], requires_grad=True)]


In [39]:
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [42]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

nb_epochs = 2000

for epoch in range(nb_epochs+1):
    # H(x) 계산
    prediction = model(x_train)
    #cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    #cost로 H(x)개선하는 부분
    #gradient를 0으로 초기화
    optimizer.zero_grad()
    #비용함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()
    
    
    if epoch %100 == 0:
        # 100번마다 로그 출력
        print("Epoch {:4d}/{} Cost:{:.6f}".format(
            epoch, nb_epochs, cost.item()
        )
              )


print(list(model.parameters()))

Epoch    0/2000 Cost:0.000001
Epoch  100/2000 Cost:0.000000
Epoch  200/2000 Cost:0.000000
Epoch  300/2000 Cost:0.000000
Epoch  400/2000 Cost:0.000000
Epoch  500/2000 Cost:0.000000
Epoch  600/2000 Cost:0.000000
Epoch  700/2000 Cost:0.000000
Epoch  800/2000 Cost:0.000000
Epoch  900/2000 Cost:0.000000
Epoch 1000/2000 Cost:0.000000
Epoch 1100/2000 Cost:0.000000
Epoch 1200/2000 Cost:0.000000
Epoch 1300/2000 Cost:0.000000
Epoch 1400/2000 Cost:0.000000
Epoch 1500/2000 Cost:0.000000
Epoch 1600/2000 Cost:0.000000
Epoch 1700/2000 Cost:0.000000
Epoch 1800/2000 Cost:0.000000
Epoch 1900/2000 Cost:0.000000
Epoch 2000/2000 Cost:0.000000
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([2.0421e-05], requires_grad=True)]


### 로지스틱 회귀모형

In [43]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [44]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [45]:
y_hat = model(x_train)

In [48]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    
    #H(x)계산
    hypothesis = model(x_train)
    
    #Cost계산
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    #Cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #20번마다 로그 출력
    if epoch%20 ==0:
        # 예측값이 0.5 넘으면 True
        prediction = hypothesis >= torch.FloatTensor([0.5])
        # 실제값과 일치하는 경우만 True
        correct_prediction = prediction.float() == y_train
        # 정확도 계산
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        
        print("Epoch {:4d}/{} Cost: {:.6f} Accuracy: {:2.2f}%".format(
            epoch, nb_epochs, cost.item(), accuracy*100
        ))

Epoch    0/1000 Cost: 1.770649 Accuracy: 50.00%
Epoch   20/1000 Cost: 0.520903 Accuracy: 83.33%
Epoch   40/1000 Cost: 0.346186 Accuracy: 83.33%
Epoch   60/1000 Cost: 0.205374 Accuracy: 83.33%
Epoch   80/1000 Cost: 0.148449 Accuracy: 100.00%
Epoch  100/1000 Cost: 0.128891 Accuracy: 100.00%
Epoch  120/1000 Cost: 0.114122 Accuracy: 100.00%
Epoch  140/1000 Cost: 0.102445 Accuracy: 100.00%
Epoch  160/1000 Cost: 0.092980 Accuracy: 100.00%
Epoch  180/1000 Cost: 0.085152 Accuracy: 100.00%
Epoch  200/1000 Cost: 0.078568 Accuracy: 100.00%
Epoch  220/1000 Cost: 0.072952 Accuracy: 100.00%
Epoch  240/1000 Cost: 0.068102 Accuracy: 100.00%
Epoch  260/1000 Cost: 0.063871 Accuracy: 100.00%
Epoch  280/1000 Cost: 0.060146 Accuracy: 100.00%
Epoch  300/1000 Cost: 0.056841 Accuracy: 100.00%
Epoch  320/1000 Cost: 0.053887 Accuracy: 100.00%
Epoch  340/1000 Cost: 0.051231 Accuracy: 100.00%
Epoch  360/1000 Cost: 0.048830 Accuracy: 100.00%
Epoch  380/1000 Cost: 0.046648 Accuracy: 100.00%
Epoch  400/1000 Cost: 0.

In [49]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [50]:
model = BinaryClassifier()

In [54]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000
for epoch in range(nb_epochs+1):
    #H(x)계산
    hypothesis = model(x_train)
    
    #cost계산
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    #cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    #20번마다 로그 출력
    if epoch % 20 == 0:
        prediction = hypothesis >=torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train 
        accuracy = correct_prediction.sum().item()/len(correct_prediction)   
        print("Epoch{:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%".format(
            epoch, nb_epochs, cost.item(), accuracy*100
        ))

Epoch   0/1000 Cost: 0.636346 Accuracy 50.00%
Epoch  20/1000 Cost: 0.380800 Accuracy 83.33%
Epoch  40/1000 Cost: 0.271243 Accuracy 83.33%
Epoch  60/1000 Cost: 0.185655 Accuracy 100.00%
Epoch  80/1000 Cost: 0.145254 Accuracy 100.00%
Epoch 100/1000 Cost: 0.126625 Accuracy 100.00%
Epoch 120/1000 Cost: 0.112351 Accuracy 100.00%
Epoch 140/1000 Cost: 0.101023 Accuracy 100.00%
Epoch 160/1000 Cost: 0.091813 Accuracy 100.00%
Epoch 180/1000 Cost: 0.084177 Accuracy 100.00%
Epoch 200/1000 Cost: 0.077741 Accuracy 100.00%
Epoch 220/1000 Cost: 0.072241 Accuracy 100.00%
Epoch 240/1000 Cost: 0.067484 Accuracy 100.00%
Epoch 260/1000 Cost: 0.063329 Accuracy 100.00%
Epoch 280/1000 Cost: 0.059667 Accuracy 100.00%
Epoch 300/1000 Cost: 0.056414 Accuracy 100.00%
Epoch 320/1000 Cost: 0.053504 Accuracy 100.00%
Epoch 340/1000 Cost: 0.050886 Accuracy 100.00%
Epoch 360/1000 Cost: 0.048516 Accuracy 100.00%
Epoch 380/1000 Cost: 0.046362 Accuracy 100.00%
Epoch 400/1000 Cost: 0.044394 Accuracy 100.00%
Epoch 420/1000 C

### 소프트맥스 회귀모형

In [55]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [56]:
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [57]:
y_one_hot = torch.zeros(8,3)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot.shape)

torch.Size([8, 3])


In [58]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3) # Output이 3!

    def forward(self, x):
        return self.linear(x)

In [59]:
model = SoftmaxClassifierModel()

In [60]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.cross_entropy(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 20== 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 2.606828
Epoch   20/1000 Cost: 1.027093
Epoch   40/1000 Cost: 0.876387
Epoch   60/1000 Cost: 0.802816
Epoch   80/1000 Cost: 0.759394
Epoch  100/1000 Cost: 0.729634
Epoch  120/1000 Cost: 0.706820
Epoch  140/1000 Cost: 0.687958
Epoch  160/1000 Cost: 0.671568
Epoch  180/1000 Cost: 0.656838
Epoch  200/1000 Cost: 0.643285
Epoch  220/1000 Cost: 0.630599
Epoch  240/1000 Cost: 0.618574
Epoch  260/1000 Cost: 0.607064
Epoch  280/1000 Cost: 0.595964
Epoch  300/1000 Cost: 0.585195
Epoch  320/1000 Cost: 0.574697
Epoch  340/1000 Cost: 0.564424
Epoch  360/1000 Cost: 0.554338
Epoch  380/1000 Cost: 0.544411
Epoch  400/1000 Cost: 0.534617
Epoch  420/1000 Cost: 0.524938
Epoch  440/1000 Cost: 0.515357
Epoch  460/1000 Cost: 0.505859
Epoch  480/1000 Cost: 0.496432
Epoch  500/1000 Cost: 0.487067
Epoch  520/1000 Cost: 0.477755
Epoch  540/1000 Cost: 0.468488
Epoch  560/1000 Cost: 0.459259
Epoch  580/1000 Cost: 0.450062
Epoch  600/1000 Cost: 0.440892
Epoch  620/1000 Cost: 0.431745
Epoch  6