### Norm :  벡터의 크기

정의. $R^n$의 벡터 $ x= (x_1, x_2, ... , x_n)$에 대하여

$ \| \mathbf{x} \| = \sqrt{x_1^2 + x_2^2 + \cdots + x_n^2}
$



### 벡터의 내적 

정의. 
$(\mathbf{x}, \mathbf{y})= x_1y_2+x_2y_2  + ... + x_ny_n$



### 벡터의 유사도

$ \| \mathbf{x-y} \| = \sqrt{(x_1^2 -y_1^2)^2+ (x_2^2 -y_2^2)^2 + \cdots +(x_n^2 -y_n^2)^2}
$


### 코사인 유사도

$\text{cosine similarity}(\mathbf{u}, \mathbf{v}) = \frac{\langle \mathbf{u}, \mathbf{v} \rangle}{\| \mathbf{u} \| \| \mathbf{v} \|}$


In [8]:
import torch
import math
import torch.nn as nn

#### 노름(Norm) 구하기

In [10]:
m1 = torch.FloatTensor([1,2])

torch.norm(m1)

tensor(2.2361)

In [7]:
math.sqrt(math.pow(1,2)+ math.pow(2,2))

2.23606797749979

#### 코사인 유사도 구하기

In [9]:
vec1 = torch.FloatTensor([1,1])
vec2 = torch.FloatTensor([2,2])
cos = nn.CosineSimilarity(dim = 0)
loss = cos(vec1, vec2)
loss

tensor(1.0000)

### Linear Regression

> Least Squared Method (최소제곱법, 최소자승법)
>
>MSE= $ \frac {1}{N} \displaystyle\sum^N_{i=1}(y_i- \hat{y_i}^2) $
>
> 고르게 오차가 생기는 것을 지향,. 한 가지 오차가 큰 것에 패널티를 주도록 한다.
>
> 
> 손실함수: 잔차의 제곱
> 
> 비용함수: 잔차 제곱의 합
> 
> 목적함수: 잔체 제곱의 합을 최소로 함


 미분을 하기?
 
>Optimizer : loss가 최소값인 지점을 찾는다.
>
>$ y = W_x + b$
>- Gradient = $ \frac {\delta loss}{\delta W}$
>
>- $ W_{new} = W - \alpha \frac {\delta loss}{\delta W}$
>
>- $\alpha$ 는 학습률

### Logistic Regression

> 독립 변수의 선형 결합으로 종속 변수를 설명
>
> 종속 변수가 범주형 데이터
>
> 각 독립변수를 입력으로 받아서 종속 변수의 특정 클래스로 분류하는 것이 목적
>
> 입력 값의 범위 $(-\infty ~ +\infty)$
> 

- Odds Ratio 는 성공 확률이 실패 확률의 몇 배인지를 나타내는 값
  - (성공, 실패) 확률이 (p(x), 1-p(x))
  - Odds Ratio = $\frac {p(x) }{1-p(x)}$

  - 일반적으로 Odds에 로그를 취한 Log-Odds 사용
    - 확률 $p_+ (x)$에 대한 Log-Odds f(x)

BCE (Binary Cross Entropy) = $\frac{1}{N}\displaystyle\sum^N_{i=0}y_i * log(\hat{y}_i) + (1-y_i) * log(1-\hat{y}_i)$

> $\hat{y}$ : 예측값, y: 실제값
>
> $cost(W) = -\displaystyle\sum^k_{j=1}y_jlog(p_j)$     $\space\space$ * softmax의 비용함수도 이와 같다

### Softmax Regression (1,2,3)


$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_{j=1}^{N} e^{x_j}}$    $\space\space$ 

softmax 비용함수

> $cost(W) = -\displaystyle\sum^n_{i=1}\displaystyle\sum^k_{j=1}y_j^{(i)}log(p_j^{(i)})$  

#### 선형회귀모형

In [11]:
import torch
import numpy as np
import torch.nn as nn               #딥러닝 관련 모듈
import torch.optim as optim     
import torch.nn.functional as F #손실함수 관련 모듈

In [12]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [14]:
x_train, x_train.shape

(tensor([[1.],
         [2.],
         [3.]]),
 torch.Size([3, 1]))

In [15]:
y_train, y_train.shape

(tensor([[2.],
         [4.],
         [6.]]),
 torch.Size([3, 1]))

y = Wx + b

In [18]:
W = torch.zeros(1, requires_grad=True)                  # W 파라미터 만들기. 0이 하나 들어있다. gradient descent 쓸것.
print(W)

tensor([0.], requires_grad=True)


In [19]:
b = torch.zeros(1, requires_grad=True)                  # b 파라미터 만들기. 0이 하나 들어있다. gradient descent 쓸것.
print(b)

tensor([0.], requires_grad=True)


In [21]:
y_hat = W*x_train + b
y_hat

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

y 와 $\hat{y}$의 차이(오차) 구하기

In [23]:
cost = torch.mean((y_train - y_hat)**2)   #**2는 제곱
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [38]:
optimizer = optim.SGD([W,b], lr = 0.01)     # lr은 학습률 = alpha

optimizer.zero_grad()    #optimizer 초기화
cost.backward()              # W의 업데이트를 위한 코드
optimizer.step()            # W(가중치) 업데이트

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [39]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    y_hat = x_train * W + b

    # cost 계산
    cost = torch.mean((y_hat - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

nn.linear

In [34]:
input_dim = 1
output_dim = 1

model = nn.Linear(input_dim, output_dim)

In [35]:
cost = F.mse_loss(y_hat, y_train)

In [36]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.3019]], requires_grad=True), Parameter containing:
tensor([-0.3271], requires_grad=True)]


In [40]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
# W = torch.zeros(1, requires_grad=True)
# b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    y_hat = x_train * W + b

    # cost 계산
    cost = torch.mean((y_hat - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))
        

Epoch    0/1999 W: 1.997, b: 0.006 Cost: 0.000005
Epoch  100/1999 W: 1.998, b: 0.005 Cost: 0.000003
Epoch  200/1999 W: 1.998, b: 0.004 Cost: 0.000002
Epoch  300/1999 W: 1.999, b: 0.003 Cost: 0.000001
Epoch  400/1999 W: 1.999, b: 0.002 Cost: 0.000001
Epoch  500/1999 W: 1.999, b: 0.002 Cost: 0.000000
Epoch  600/1999 W: 1.999, b: 0.001 Cost: 0.000000
Epoch  700/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  800/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch  900/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1000/1999 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1100/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1200/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1300/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1400/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1500/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1600/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/1999 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/1999 W: 2.000, b: 0.000 Cost: 0.000000


#### 로지스틱 회귀모형

In [43]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0],[0],[0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [44]:
model = nn.Sequential(
    nn.Linear(2,1),
    nn.Sigmoid()
)

In [45]:
model(x_train)   # 각각이 1로 분류될 수 있는 확률.

tensor([[0.1778],
        [0.0888],
        [0.1038],
        [0.0364],
        [0.0230],
        [0.0198]], grad_fn=<SigmoidBackward0>)

In [46]:
y_hat = model(x_train)

In [47]:
# y_hat >0.5

tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False]])

In [50]:

optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    y_hat = x_train * W + b
    hypothesis = model(x_train)
    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        
        print('Epoch {:4d}/{} Cost: {:.6f}, Accuracy: {:2.2f}'.format(
            epoch, nb_epochs,cost.item(), accuracy*100,
        ))

Epoch    0/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   10/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   20/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   30/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   40/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   50/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   60/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   70/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   80/1000 Cost: 1.901183, Accuracy: 50.00
Epoch   90/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  100/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  110/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  120/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  130/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  140/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  150/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  160/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  170/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  180/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  190/1000 Cost: 1.901183, Accuracy: 50.00
Epoch  200/1000 Cost: 1.901183, Accuracy

In [51]:
class BinaryClassifier (nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [53]:
model = BinaryClassifier()

In [54]:

optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    y_hat = x_train * W + b
    hypothesis = model(x_train)
    # cost 계산
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        
        print('Epoch {:4d}/{} Cost: {:.6f}, Accuracy: {:2.2f}'.format(
            epoch, nb_epochs,cost.item(), accuracy*100,
        ))

Epoch    0/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   10/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   20/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   30/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   40/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   50/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   60/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   70/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   80/1000 Cost: 1.025021, Accuracy: 33.33
Epoch   90/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  100/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  110/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  120/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  130/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  140/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  150/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  160/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  170/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  180/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  190/1000 Cost: 1.025021, Accuracy: 33.33
Epoch  200/1000 Cost: 1.025021, Accuracy

softmax

In [56]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [58]:
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [59]:
y_one_hot = torch.zeros(8, 3)
y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)
print(y_one_hot.shape)


torch.Size([8, 3])


In [66]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4, 3) # Output이 3!

    def forward(self, x):
        return self.linear(x)

In [67]:

optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산

    prediction = model(x_train)
    # cost 계산
    cost = F.cross_entropy(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 20번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (8x4 and 2x1)